### ISSUE TITLE
`devicePixelRatio` for `FixedScrollMetrics` class is not provided

### ISSUE THREAD

**Issue by maple135790** [GeekyAnts/infinite-carousel-flutter#10]
since flutter PR in flutter/flutter#117503, `FixedScrollMetrics` is requiring a `devicePixelRatio` parameter, which is missing in the code
will make a PR to fix this issue.

![image](https://github.com/GeekyAnts/infinite-carousel-flutter/assets/29313331/26ea92c2-b298-471d-b9cb-388f36e2e2c2)

**Comment by maple135790** [comment]
related PR #11

**Comment by manuindersekhon** [comment]
Merged and released [v1.0.3](https://pub.dev/packages/infinite_carousel/versions/1.0.3). Thanks for the PR.
