### ISSUE TITLE
automatic height

### ISSUE THREAD

**Issue by z0rgoyok** [GeekyAnts/infinite-carousel-flutter#15]
Why do I need to put the widget in a container with a fixed height? 
What should I do if I need automatic height? 

Thanks <3

**Comment by manuindersekhon** [comment]
Hi @z0rgoyok , thanks for using the package. 
Basically it expands to take up all the available space, just like PageView behaves.

Alternatively, you can wrap it in `Expanded` without needing to give the fixed height. I hope it helps.
```dart
Column(
  children: [
    // other widgets ...
    Expanded(
      child: InfiniteCarousel.builder(
        itemCount: 10,
        itemExtent: 120,
        center: true,
        anchor: 0.0,
        velocityFactor: 0.2,
        onIndexChanged: (index) {},
        axisDirection: Axis.horizontal,
        loop: true,
        itemBuilder: (context, itemIndex, realIndex) {},
      ),
    ),
    // Other widgets ...
  ],
),
```
