### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Welnnys** [GeekyAnts/infinite-carousel-flutter#21]
Is there a way I can make it start the carousel from the second item instead of the first?

https://pastebin.com/ZLxsMdUb

**Comment by manuindersekhon** [comment]
@Welnnys , you can pass `initialItem` argument to `InfiniteScrollController`
Eg, `InfiniteScrollController(initialItem: 1)`

**Comment by Welnnys** [comment]
works flawlessly, thank you :3
