### ISSUE TITLE
space between items

### ISSUE THREAD

**Issue by alish-sw** [GeekyAnts/infinite-carousel-flutter#27]
Hi I use your great package in my project,but i have a problem with use package that is add space between item look like the use pic that your team upload in pub dev,please help me.tnx

**Comment by manuindersekhon** [comment]
Hi @alish-sw, that is the Padding on top of every item that created the space in the example.  You can refer to https://github.com/GeekyAnts/infinite-carousel-flutter/blob/main/example/lib/screens/horizontal.dart file `itemBuilder` section to look more on the source code for the examlpe pics.

I hope it clears your query. Please let me know in case anything else is needed. Thanks.
