### ISSUE TITLE
[Question] Scaling Selected Item

### ISSUE THREAD

**Issue by seanocali** [GeekyAnts/infinite-carousel-flutter#9]
The first GIF on the pub.dev page shows the selected item scale animation as you scroll. Is that functionality part of this package or just done using other widgets?

**Comment by manuindersekhon** [comment]
Hi @seanocali, it's not built into the package. It is part of the example included with this package.
[Example link](https://github.com/GeekyAnts/infinite-carousel-flutter/blob/main/example/lib/screens/complex.dart)
